name: Build macOS Qt App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest  # 修正这里
    # 或者使用具体版本：macos-13、macos-12、macos-11

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: mac
        target: desktop

    - name: Build Project
      run: |
        cd src
        qmake baojia.pro
        make -j4
    # ---------- 第四步：打包 .app ----------
    - name: Package Application
      run: |
        cd src
        
        # 使用 macdeployqt 打包依赖库
        macdeployqt baojia.app -verbose=1
        
        # 创建 DMG 安装包（可选）
        hdiutil create -volname "baojia" \
          -srcfolder baojia.app \
          -ov -format UDZO baojia.dmg

    # ---------- 第五步：上传构建产物 ----------
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: baojia-macOS
        path: |
          src/baojia.app
          src/baojia.dmg
        retention-days: 7    # 保留7天